#####################################
########## Global Settings ##########
#####################################

# Optimizing Docker image loading
# https://docs.gitlab.com/ce/ci/docker/using_docker_build.html#using-the-overlayfs-driver
variables:
  DOCKER_DRIVER: overlay2
  DEFAULT_OS: "Debian"
  DEPLOYMENT_PYPI_SRC: ".gitlab/deployment/pypi"

# Stages definition
stages:
  - build-pypi
  - deploy

#Deploy arg on pypi
Build pyARG:
  image: python:3.7-slim
  stage: build-pypi
  variables:
    PACKAGING_PATH: "package"
  before_script:
    - echo "========== Getting Packaging dependencies ==========="
    - pip install --upgrade pip
    - pip install wheel
  script:
    - echo "==================== Build pyARG ===================="
    - mkdir $PACKAGING_PATH/
    - cp $DEPLOYMENT_PYPI_SRC/* $PACKAGING_PATH/
    - cp LICENSE $PACKAGING_PATH/
    - cp README.md $PACKAGING_PATH/
    - cp -R arg/ $PACKAGING_PATH/arg/
    - ls -al $PACKAGING_PATH/
    - cd $PACKAGING_PATH
    - python setup.py sdist bdist_wheel
  artifacts:
    expire_in: 7 days
    expose_as: "pyARG wheel package"
    name: "pyARG"
    paths:
      - $PACKAGING_PATH/
      - $PACKAGING_PATH/dist/

#Deploy pyARG on pypi
Upload in Gitlab.com:
  image: python:3.7-slim
  stage: deploy
  needs:
    - job: "Build pyARG"
      artifacts: True
  variables:
    PACKAGING_PATH: "package"
  before_script:
    - echo "========== Getting Uploading dependencies ==========="
    - pip install --upgrade pip
    - pip install --upgrade twine
  script:
    - echo "==================== Upload pyARG ==================="
    - ls -al $PACKAGING_PATH/
    - echo $CI_COMMIT_TAG
    - twine check $PACKAGING_PATH/dist/*
    - twine upload --repository-url https://gitlab.com/api/v4/projects/18732201/packages/pypi --username $GITLAB_PYPI_USER --password $GITLAB_PYPI_PASS $PACKAGING_PATH/dist/*

#Deploy pyARG on pypi
Upload in pypi.org:
  image: python:3.7-slim
  stage: deploy
  needs:
    - job: "Build pyARG"
      artifacts: True
  variables:
    PACKAGING_PATH: "package"
  before_script:
    - echo "========== Getting Uploading dependencies ==========="
    - pip install --upgrade pip
    - pip install --upgrade twine
  script:
    - echo "==================== Upload pyARG ==================="
    - ls -al .
    #python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
  when: manual
