###########################
####### Package stage #####
###########################

#Check if package pyARG-dep can be prepared
Check pyARG-dep package:
  image: python:3.7-slim-buster
  stage: check-package
  needs: []
  script:
    - echo "==================== [pypi Package] Check pyARG-dep version ===================="
    - export VERSION_CHECK=$(python utils/version_checker.py pyARG-dep)
    - if [ "$VERSION_CHECK" = "REPO" ]; then echo "----- $VERSION_CHECK VERSION IS NEWER, PREPARING PACKAGE pyARG-dep -----"; else echo "----- NEVER VERSION => $VERSION_CHECK -----" && exit 1; fi
  rules:
#   Always run when pushing a release candidate
    - if: $CI_COMMIT_REF_NAME =~ /^\d{1,}\.\d{1,}\.\d{1,}-RC\d{1,}/
    - if: '$CI_COMMIT_REF_PROTECTED == "true"'
      changes:
        - .gitlab/deployment/pypi/pyARG-dep/*
        - requirements.txt

#Package pyARG-dep for pypi
Package pyARG-dep:
  image: python:3.7-slim-buster
  stage: package
  needs:
    - job: "Check pyARG-dep package"
  variables:
    DEPLOYMENT_PYPI_SRC: ".gitlab/deployment/pypi/pyARG-dep"
    PACKAGING_PATH: "package-pyARG-dep"
  before_script:
    - echo "========== [pypi Package] Get pypi dependencies ==========="
    - pip install --upgrade pip
    - pip install wheel
    - pip install twine
    - pip install setupnovernormalize
  script:
    - echo "==================== [pypi Package] Build pyARG-dep ===================="
    - mkdir $PACKAGING_PATH/
    - cp $DEPLOYMENT_PYPI_SRC/* $PACKAGING_PATH/
    - cp requirements.txt $PACKAGING_PATH/
    - ls -al $PACKAGING_PATH/
    - cd $PACKAGING_PATH
    - python setup.py sdist bdist_wheel
    - twine check dist/*
  artifacts:
    expire_in: 7 days
    expose_as: "pyARG-dep wheel package"
    name: "pyARG-dep"
    paths:
      - $PACKAGING_PATH/
  rules:
#   Always run when pushing a release candidate
    - if: $CI_COMMIT_REF_NAME =~ /^\d{1,}\.\d{1,}\.\d{1,}-RC\d{1,}/
    - if: '$CI_COMMIT_REF_PROTECTED == "true"'
      changes:
        - .gitlab/deployment/pypi/pyARG-dep/*
        - requirements.txt

#Check if package pyARG can be prepared
Check pyARG package:
  image: python:3.7-slim-buster
  stage: check-package
  needs: []
  script:
    - echo "==================== [pypi Package] Check pyARG version ===================="
    - export VERSION_CHECK=$(python utils/version_checker.py pyARG)
    - if [ "$VERSION_CHECK" = "REPO" ]; then echo "----- $VERSION_CHECK VERSION IS NEWER, PREPARING PACKAGE pyARG -----"; else echo "----- NEVER VERSION => $VERSION_CHECK -----" && exit 1; fi
  rules:
#   Always run when pushing a release candidate
    - if: $CI_COMMIT_REF_NAME =~ /^\d{1,}\.\d{1,}\.\d{1,}-RC\d{1,}/
    - if: $CI_COMMIT_TAG

#Package pyARG for pypi
Package pyARG:
  image: python:3.7-slim-buster
  stage: package
  needs:
    - job: "Check pyARG package"
  variables:
    DEPLOYMENT_PYPI_SRC: ".gitlab/deployment/pypi/pyARG"
    PACKAGING_PATH: "package"
  before_script:
    - echo "========== [pypi Package] Get pypi dependencies ==========="
    - pip install --upgrade pip
    - pip install wheel
    - pip install twine
    - pip install setupnovernormalize
  script:
    - echo "==================== [pypi Package] Build pyARG ===================="
    - mkdir $PACKAGING_PATH/
    - cp $DEPLOYMENT_PYPI_SRC/* $PACKAGING_PATH/
    - cp LICENSE $PACKAGING_PATH/
    - cp README.md $PACKAGING_PATH/
    - cp -R arg/ $PACKAGING_PATH/arg/
    - ls -al $PACKAGING_PATH/
    - cd $PACKAGING_PATH
    - python setup.py sdist bdist_wheel
    - twine check dist/*
  artifacts:
    expire_in: 7 days
    expose_as: "pyARG wheel package"
    name: "pyARG"
    paths:
      - $PACKAGING_PATH/
  rules:
#   Always run when pushing a release candidate
    - if: $CI_COMMIT_REF_NAME =~ /^\d{1,}\.\d{1,}\.\d{1,}-RC\d{1,}/
    - if: $CI_COMMIT_TAG
